# Generated by Django 5.0.14 on 2025-09-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSpreadBollinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secret_key', models.TextField()),
                ('jwt_token', models.TextField()),
                ('account_id', models.CharField(max_length=100)),
                ('base_symbol', models.CharField(max_length=100)),
                ('symbol1', models.CharField(max_length=100)),
                ('symbol2', models.CharField(max_length=100)),
                ('step_price', models.FloatField()),
                ('lot_max', models.IntegerField()),
                ('lot_work', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BollingerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(blank=True, default=0, null=True)),
                ('level_high', models.IntegerField(blank=True, default=0, null=True)),
                ('level_low', models.IntegerField(blank=True, default=0, null=True)),
                ('period', models.IntegerField(blank=True, default=0, null=True)),
                ('deviation', models.FloatField(blank=True, default=0, null=True)),
                ('level_type', models.CharField(choices=[('sma', 'sma'), ('high', 'high'), ('low', 'lowr')], help_text='bollinger type', max_length=30)),
                ('level_price', models.FloatField(blank=True, default=0, null=True)),
                ('normal_price', models.FloatField(blank=True, default=0, null=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('side', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('limit_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moex.botspreadbollinger')),
            ],
        ),
    ]
