# Generated by Django 5.0.14 on 2025-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerlevel',
            name='level_sma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
