# Generated by Django 5.0.14 on 2025-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0002_bollingerlevel_level_sma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bollingerlevel',
            options={'ordering': ('level_id',)},
        ),
        migrations.AlterField(
            model_name='bollingerlevel',
            name='level_type',
            field=models.CharField(choices=[('sma', 'sma'), ('high', 'high'), ('low', 'low')], help_text='bollinger type', max_length=30),
        ),
    ]
