# Generated by Django 5.0.14 on 2025-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0003_alter_bollingerlevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botspreadbollinger',
            name='ask',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botspreadbollinger',
            name='bid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botspreadbollinger',
            name='last',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botspreadbollinger',
            name='side',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('s', 's'), ('n', 'n')], default='n', help_text='side', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='botspreadbollinger',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
