# Generated by Django 5.0.14 on 2025-09-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0004_botspreadbollinger_ask_botspreadbollinger_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerlevel',
            name='level_work',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
