# Generated by Django 5.0.14 on 2025-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0005_bollingerlevel_level_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerlevel',
            name='level_stop_high',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bollingerlevel',
            name='level_stop_low',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
