# Generated by Django 5.0.14 on 2025-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0006_bollingerlevel_level_stop_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerlevel',
            name='level_side',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
