# Generated by Django 5.0.14 on 2025-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0007_bollingerlevel_level_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerlevel',
            name='order_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
