# Generated by Django 5.0.14 on 2025-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0008_bollingerlevel_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('secret_key', models.TextField()),
                ('jwt_token', models.TextField()),
            ],
        ),
    ]
