# Generated by Django 5.0.14 on 2025-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentGateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_rate', models.FloatField(default=0)),
                ('cycle', models.CharField(max_length=20)),
                ('settle_fee_rate', models.FloatField(default=0)),
                ('in_delisting', models.BooleanField()),
                ('expire_time', models.IntegerField()),
                ('risk_limit_base', models.FloatField(default=0)),
                ('index_price', models.FloatField(default=0)),
                ('order_price_round', models.FloatField(default=0)),
                ('order_size_min', models.IntegerField()),
                ('ref_rebate_rate', models.FloatField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('ref_discount_rate', models.FloatField(default=0)),
                ('order_price_deviate', models.FloatField(default=0)),
                ('maintenance_rate', models.FloatField(default=0)),
                ('mark_type', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('basis_value', models.FloatField(default=0)),
                ('leverage_min', models.FloatField(default=0)),
                ('settle_price_interval', models.IntegerField()),
                ('last_price', models.FloatField(default=0)),
                ('mark_price', models.FloatField(default=0)),
                ('order_size_max', models.IntegerField()),
                ('maker_fee_rate', models.FloatField(default=0)),
                ('settle_price_duration', models.IntegerField()),
                ('config_change_time', models.IntegerField()),
                ('orderbook_id', models.IntegerField()),
                ('trade_size', models.IntegerField()),
                ('underlying', models.CharField(max_length=50)),
                ('position_size', models.IntegerField()),
                ('orders_limit', models.IntegerField()),
                ('quanto_multiplier', models.FloatField(default=0)),
                ('basis_impact_value', models.FloatField(default=0)),
                ('mark_price_round', models.FloatField(default=0)),
                ('settle_price', models.FloatField(default=0)),
                ('leverage_max', models.FloatField(default=0)),
                ('risk_limit_max', models.IntegerField()),
                ('taker_fee_rate', models.FloatField(default=0)),
                ('trade_id', models.IntegerField()),
                ('risk_limit_step', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PairGateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_symbol', models.CharField(max_length=10)),
                ('symbol1', models.CharField(max_length=100)),
                ('symbol2', models.CharField(max_length=100)),
                ('is_updata', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('symbol1', 'symbol2')},
            },
        ),
    ]
