# Generated by Django 5.0.14 on 2025-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentgateio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
