# Generated by Django 5.0.14 on 2025-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateio', '0002_instrumentgateio_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairgateio',
            name='spot1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pairgateio',
            name='spot2',
            field=models.BooleanField(default=False),
        ),
    ]
