# Generated by Django 5.0.14 on 2025-08-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateio', '0003_pairgateio_spot1_pairgateio_spot2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairgateio',
            old_name='spot1',
            new_name='delivery1',
        ),
        migrations.RenameField(
            model_name='pairgateio',
            old_name='spot2',
            new_name='delivery2',
        ),
    ]
