# Generated by Django 5.0.14 on 2025-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateio', '0005_barspreadgateio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentgateio',
            name='is_updata',
            field=models.BooleanField(default=True),
        ),
    ]
