# Generated by Django 5.0.14 on 2025-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateio', '0008_alter_barspreadgateio_last1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barspreadgateio',
            name='fair1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspreadgateio',
            name='fair2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspreadgateio',
            name='funding',
            field=models.FloatField(default=0, null=True),
        ),
    ]
