# Generated by Django 5.0.14 on 2025-10-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex_smart_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmart',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moex_smart_order.botsmart'),
        ),
    ]
