# Generated by Django 5.0.14 on 2025-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex_smart_order', '0002_ordersmart_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsmart',
            name='bot_side',
            field=models.CharField(choices=[('b', 'b'), ('s', 's'), ('n', 'n')], default='n', help_text='side', max_length=3),
        ),
        migrations.AddField(
            model_name='botsmart',
            name='value_max',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
