# Generated by Django 5.0.14 on 2025-11-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex_smart_order', '0003_botsmart_bot_side_botsmart_value_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmart',
            name='circulation',
        ),
        migrations.RemoveField(
            model_name='ordersmart',
            name='pater',
        ),
        migrations.AddField(
            model_name='botsmart',
            name='range_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ordersmart',
            name='level_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ordersmart',
            name='level_queue',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
