# Generated by Django 5.0.14 on 2025-11-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moex_smart_order', '0005_alter_ordersmart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmart',
            options={'ordering': ('level_id',)},
        ),
    ]
