# Generated by Django 5.0.14 on 2025-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex_smart_order', '0006_alter_ordersmart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsmart',
            name='step_price',
            field=models.FloatField(default=0),
        ),
    ]
