# Generated by Django 5.0.14 on 2025-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barspread',
            name='last1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barspread',
            name='last2',
            field=models.FloatField(default=0),
        ),
    ]
