# Generated by Django 5.0.14 on 2025-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_barspread_last1_alter_barspread_last2'),
    ]

    operations = [
        migrations.AddField(
            model_name='barspread',
            name='fair1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspread',
            name='fair2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspread',
            name='funding',
            field=models.FloatField(default=0, null=True),
        ),
    ]
