# Generated by Django 5.0.14 on 2025-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binans', '0002_barspreadbinans_last1_barspreadbinans_last2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barspreadbinans',
            name='last1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='barspreadbinans',
            name='last2',
            field=models.FloatField(default=0, null=True),
        ),
    ]
