# Generated by Django 5.0.14 on 2025-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binans', '0003_alter_barspreadbinans_last1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barspreadbinans',
            name='fair1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspreadbinans',
            name='fair2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='barspreadbinans',
            name='funding',
            field=models.FloatField(default=0, null=True),
        ),
    ]
